Creating a nav br
CodingCerrado/portfolio-pessoal pull request #10
Opened 2022-10-25 22:54 UTC by Jeffersonlpu

2022-11-01 13:05 UTC, jhrodriguesit requested changes
Excelente trabalho @Jeffersonlpu!!
Estou impressionado, mandou bem demais muito orgulho!!
Deixei apenas algumas pequenas mudanças/dicas na revisão.

2022-11-01 13:05 UTC, jhrodriguesit commented on index.html
> +          |
```suggestion
```
Poderia remover esses traços e utilizar a propriedade `border-left` no css para gerar essa linha entre os links?

2022-11-01 13:05 UTC, jhrodriguesit commented on styles.css
> +  padding: 0 2.4rem;
```suggestion
  padding: 1rem 2.4rem;
```
O que acha, sobre adicionar um padding horizontal para ficar mais parecido com o nosso template?

2022-11-01 13:05 UTC, jhrodriguesit commented on styles.css
> +}
```suggestion
nav img.logo {
  width: 2.5rem;
}
```
Seria interessante definir esse estilo apenas para o logo dentro do elemento `nav`

2022-11-01 13:05 UTC, jhrodriguesit commented on styles.css
> +ul {
```suggestion
nav ul {
```
Quando voce define o estilo usando apenas o elemento `ul` esse estilo vai ser aplicado para qualquer outra listas que criarmos. Por isso é interessante definir que esse estilo é apenas para a `ul` que pertence ao `nav`.
Seria interessante criarmos classes ou id's para os nossos elementos html, assim vai ficar mais facil nao nos perdermos quando o codigo ficar maior (podemos discutir isso na nossa proxima reuniao).

2022-11-01 13:05 UTC, jhrodriguesit commented on styles.css
>    font-family: Arial, Helvetica, sans-serif;
```suggestion
  font-family: 'Work Sans';
```
O nosso template utiliza a fonte 'Work Sans'. Voce poderia trocar por gentileza? Nao sera apenas uma questao de mudar o nome. Da uma olhada nesse exemplo. Acho que vai te ajudar https://www.w3schools.com/howto/tryit.asp?font=Work%20Sans

2022-11-01 13:05 UTC, jhrodriguesit commented on styles.css
> +nav a {
No nosso template os links do menu mudam de cor quando passamos o mouse em cima. 
Poderia tentar implementar essa funcionalidade também?

2022-11-01 13:09 UTC, jhrodriguesit commented on styles.css
> +}
```suggestion
nav a {
  text-decoration: none;
  color: black;
}
```
Nao sei se sao realmente necessarios todos esses estilos repetindo a mesma coisa. Acho que voce pode simplesmente adicionar `color: black'` no `nav a`

2022-11-01 15:22 UTC, Jeffersonlpu commented on styles.css
>    font-family: Arial, Helvetica, sans-serif;
Sim. Sem problemas!
Eu vou deixar para commitar na nossa reunião para o pessoal ver que é possível aceitar os seus commits no meu PR.
Como você identificou a fonte?
A ferramenta que eu tentei utilizar para identificar não funcionou.

2022-11-01 15:24 UTC, jhrodriguesit commented on styles.css
> +  background-color: #f3f3f3;
```suggestion
```
Nosso site inteiro tem o mesmo background. O que acha de mover esse estilo para dentro do elemento `body`? Assim toda a pagina via ficar com a mesma cor.

2022-11-01 15:24 UTC, jhrodriguesit commented on styles.css
> +  box-sizing: border-box;
O que acha de adicionarmos ` background-color: #f3f3f3;` aqui, ja que todo o site tem a mesma cor de fundo?

2022-11-02 14:22 UTC, Jeffersonlpu commented on index.html
> +          |
Alteração feita, @jhrodriguesit

2022-11-02 19:51 UTC, Jeffersonlpu commented on styles.css
>    font-family: Arial, Helvetica, sans-serif;
Alterado!
Obrigado, @jhrodriguesit !

2022-11-02 19:56 UTC, Jeffersonlpu commented on styles.css
> +}
Realmente, @jhrodriguesit !
Valeu demais!

2022-11-02 20:00 UTC, Jeffersonlpu commented on styles.css
> +  background-color: #f3f3f3;
I've already change!
Great observation, @jhrodriguesit !

2022-11-02 20:14 UTC, Jeffersonlpu commented on styles.css
> +nav a {
I've already implemented!
Thanks, @jhrodriguesit !

2022-11-02 20:46 UTC, Jeffersonlpu commented
Estou com dois problemas para finalizar meu pull request:
1 - Não consigo fazer com que o hover fique habilitado apenas para as palavras à direita no Nav Bar. Está incluindo a palavra "Coding Cerrado". Tentei criar mais uma class, mas não soube como fazer p incluir uma segunda class na div.
2 - Gostaria de diminuir a altura do border-left para que fique menor entre as palavras à direita. Não consigo mexer nessa propriedade. Alguém sabe como é?

2022-11-05 12:31 UTC, jhrodriguesit commented
> Estou com dois problemas para finalizar meu pull request: 1 - Não consigo fazer com que o hover fique habilitado apenas para as palavras à direita no Nav Bar. Está incluindo a palavra "Coding Cerrado". Tentei criar mais uma class, mas não soube como fazer p incluir uma segunda class na div. 2 - Gostaria de diminuir a altura do border-left para que fique menor entre as palavras à direita. Não consigo mexer nessa propriedade. Alguém sabe como é? @jhrodriguesit @jacqueline-abreu @biararaujo

A altura da borda depende da altura da `div`.

2022-11-05 12:32 UTC, jhrodriguesit requested changes
Otimo trabalho @Jeffersonlpu !
Deixei mais alguns comentarios, me avisa se tiver alguma duvida!

2022-11-05 12:32 UTC, jhrodriguesit commented on styles.css
> +}
Nao queremos adicionar esse hover para manter o text que nao queremos aplicar o hover intacto. O que devemos fazer e garantir que o hover so sera aplicado nos links ("Resume" "projects", "contacts"). Para isso voce pode usar a classe que voce ja criou para a `ul` que envolve essas opcoes `right-content`. 
Seria algo mais ou menos assim:
`.right-content a:hover {
 color: rgb(150, 107, 54);
}`

Apos fazer isso, voce tb pode remover `nav a:hover {  color: rgb(150, 107, 54); }` tambem

2022-11-05 12:32 UTC, jhrodriguesit commented on index.html
> +            <div><a class="nav-hover" href="#">Resume</a></div>
Todos os links dentro dessa `ul` estao usando a classe `nav-hover` apenas para aplicar o efeito de hover. Por isso podemos simplificar adicionando `.right-content a:hover { color: rgb(150, 107, 54); }` no css. Como explicado no review do arquivo css.

2022-11-05 12:32 UTC, jhrodriguesit commented on index.html
> +            <div class="border-left">
```suggestion
            <div class="link-with-border">
```
Evite usar uma palavra reservada como nome de classe (border-left eh o nome do proprio comando que vai adicionar a borda). Lembre de atualizar o nome da classe no css tb.

2022-11-05 12:32 UTC, jhrodriguesit commented on styles.css
> +}
```suggestion
}
```

2022-11-05 14:55 UTC, Jeffersonlpu commented on styles.css
> +}
Valeu, @jhrodriguesit !
Eu acabei criando essa `right-content` depois e não percebi que poderia ter feito isso antes. Foi o jeito que deu para fazer, mas sabia que não era o ideal. Valeu pelo toque!

2022-11-05 14:58 UTC, Jeffersonlpu commented on index.html
> +            <div class="border-left">
Sim, @jhrodriguesit !
Valeu por mais essa dica!

2022-11-05 15:19 UTC, Jeffersonlpu commented
> Otimo trabalho @Jeffersonlpu ! Deixei mais alguns comentarios, me avisa se tiver alguma duvida!

Foi tranquilo resolver dessa vez, @jhrodriguesit ! Obrigado pelas dicas! Ajudou demais! Solicito novo code review para o merge!

2022-11-07 13:46 UTC, jhrodriguesit approved these changes
Excelente trabalho @Jeffersonlpu !!
Mandou bem demais!!

2022-11-07 13:46 UTC, jhrodriguesit commented on index.html
> +              Editor
```suggestion
```
Poderia por gentileza remover a palavra "Editor". Apesar de estar no template original acho que vai ficar melhor sem.

2022-11-07 14:21 UTC, merged