Creating welcome
CodingCerrado/portfolio-pessoal pull request #12
Opened 2022-11-01 23:17 UTC by jacqueline-abreu

Branch created for the welcome page.

2022-11-02 13:16 UTC, jhrodriguesit commented on style.css
> +.text1{
```suggestion
.welcome-title{
```

2022-11-02 13:45 UTC, jhrodriguesit requested changes

2022-11-02 13:45 UTC, jhrodriguesit commented on style.css
> +.text3{
```suggestion
.welcome-description
```

2022-11-02 13:46 UTC, jhrodriguesit commented on style.css
> +#text {
```suggestion
#welcome-text {
```

2022-11-06 18:25 UTC, jacqueline-abreu commented
I changed the class names and id as request.

2022-11-08 00:37 UTC, biararaujo approved these changes

2022-11-24 12:30 UTC, merged